using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;

namespace AIBox.FirstRun.Services;

/// <summary>
/// Generates the secrets the stack needs and writes them to
/// aibox/stack/.env. The .env file is owned by Administrators + SYSTEM
/// with all other ACEs stripped. We never log secret values.
/// </summary>
public static class EnvWriter
{
    public sealed class EnvInputs
    {
        public required string AdminUsername { get; init; }
        public required string AdminPassword { get; init; }
        public string AppEnv { get; init; } = "production";
        public bool SessionCookieSecure { get; init; } = false;
    }

    public sealed class EnvOutputs
    {
        public required string AdminUsername { get; init; }
        public required string AdminPassword { get; init; } // copied through for the post-install summary
        public bool AclLockedDown { get; init; } = true;
    }

    public static EnvOutputs Write(string envPath, EnvInputs input, FileLogger? log)
    {
        var entries = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            { "APP_ENV", input.AppEnv },
            { "APP_ENCRYPTION_MASTER_KEY", GenerateBase64(32) },
            { "SESSION_TOKEN_PEPPER", GenerateHex(32) },
            { "DNS_ADMIN_PASSWORD", GenerateAlphanumeric(24) },
            { "ADMIN_USERNAME", input.AdminUsername },
            { "ADMIN_DEFAULT_PASSWORD", input.AdminPassword },
            { "SESSION_COOKIE_SECURE", input.SessionCookieSecure ? "true" : "false" },
        };

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by AIBox First Run. Do not commit. Do not share.");
        sb.AppendLine("# Regenerating these values invalidates existing encrypted user data.");
        sb.AppendLine();
        foreach (var (k, v) in entries)
        {
            sb.Append(k).Append('=').AppendLine(EscapeValue(v));
        }

        Directory.CreateDirectory(Path.GetDirectoryName(envPath)!);
        var tmp = envPath + ".tmp";
        File.WriteAllText(tmp, sb.ToString(), new UTF8Encoding(false));

        using (var fs = new FileStream(tmp, FileMode.Open, FileAccess.ReadWrite, FileShare.None))
            fs.Flush(true);

        if (File.Exists(envPath)) File.Replace(tmp, envPath, null);
        else File.Move(tmp, envPath);

        bool aclOk = true;
        if (OperatingSystem.IsWindows())
            aclOk = LockDownAcls(envPath, log);

        log?.Info($"Wrote {envPath} with {entries.Count} keys." +
                  (aclOk ? " ACLs locked to Administrators + SYSTEM." : " ACL lockdown skipped (non-elevated)."));

        return new EnvOutputs
        {
            AdminUsername = input.AdminUsername,
            AdminPassword = input.AdminPassword,
            AclLockedDown = aclOk,
        };
    }

    /// <summary>
    /// DPAPI-encrypt the admin password so the post-install summary screen
    /// can re-display it. Deleted on first Control Panel launch — see
    /// FinalizePhase. Encryption scope = LocalMachine because the autostart
    /// task may run as SYSTEM and need to read this on the user's behalf.
    /// </summary>
    public static void SaveDpapiAdminBlob(string path, string adminPassword, FileLogger? log)
    {
#pragma warning disable CA1416 // Windows-only API; we ship a Windows binary
        var plain = Encoding.UTF8.GetBytes(adminPassword);
        var blob = ProtectedData.Protect(plain, null, DataProtectionScope.LocalMachine);
        Array.Clear(plain);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllBytes(path, blob);
        if (OperatingSystem.IsWindows())
            LockDownAcls(path, log); // best-effort; DPAPI blob is already machine-encrypted
        log?.Info($"Wrote DPAPI admin blob to {path}.");
#pragma warning restore CA1416
    }

    public static string ReadDpapiAdminBlob(string path)
    {
#pragma warning disable CA1416
        var blob = File.ReadAllBytes(path);
        var plain = ProtectedData.Unprotect(blob, null, DataProtectionScope.LocalMachine);
        try { return Encoding.UTF8.GetString(plain); }
        finally { Array.Clear(plain); }
#pragma warning restore CA1416
    }

    public static void DeleteDpapiAdminBlob(string path)
    {
        try { if (File.Exists(path)) File.Delete(path); } catch { /* best-effort */ }
    }

    private static string GenerateBase64(int bytes)
    {
        var buf = RandomNumberGenerator.GetBytes(bytes);
        return Convert.ToBase64String(buf);
    }

    private static string GenerateHex(int bytes)
    {
        var buf = RandomNumberGenerator.GetBytes(bytes);
        return Convert.ToHexString(buf).ToLowerInvariant();
    }

    private static string GenerateAlphanumeric(int length)
    {
        const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        var picks = new char[length];
        var buf = RandomNumberGenerator.GetBytes(length * 2);
        for (int i = 0; i < length; i++)
        {
            int idx = ((buf[i * 2] << 8) | buf[i * 2 + 1]) % chars.Length;
            picks[i] = chars[idx];
        }
        return new string(picks);
    }

    private static string EscapeValue(string v)
    {
        // .env consumers in this project (docker compose, python-dotenv) treat
        // unquoted values literally; only quote when we hit characters that
        // would confuse them. Anything generated by us is safe; the admin
        // password may contain anything the user typed.
        var needsQuote = v.Length == 0 || v.IndexOfAny(new[] { ' ', '#', '$', '"', '\'', '\\', '\n', '\r', '\t' }) >= 0;
        if (!needsQuote) return v;
        return "\"" + v.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }

    /// <returns>
    /// <c>true</c> if ACLs were locked successfully; <c>false</c> if the process is
    /// non-elevated and the failure was swallowed. Elevated runs still re-throw.
    /// </returns>
    private static bool LockDownAcls(string path, FileLogger? log)
    {
#pragma warning disable CA1416
        // The user owns files they create, so SetAccessControl would succeed even
        // non-elevated — and then lock the owning user out of their own file. That
        // is not the production guarantee (which is "only Admins+SYSTEM can read")
        // because the act of running ACL changes outside an elevated install token
        // means we cannot prove the parent directory's ACLs were not loosened. Skip
        // the lockdown rather than perform a self-mutilating change.
        if (!IsRunningElevated())
        {
            log?.Warn($"ACL lockdown skipped on {path}: process is not elevated.");
            return false;
        }
        try
        {
            var info = new FileInfo(path);
            var sec = info.GetAccessControl();
            sec.SetAccessRuleProtection(true, false); // disable inheritance, remove inherited rules

            foreach (FileSystemAccessRule rule in sec.GetAccessRules(true, false, typeof(NTAccount)))
                sec.RemoveAccessRule(rule);

            var admins = new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null);
            var system = new SecurityIdentifier(WellKnownSidType.LocalSystemSid, null);

            sec.AddAccessRule(new FileSystemAccessRule(admins,
                FileSystemRights.FullControl, AccessControlType.Allow));
            sec.AddAccessRule(new FileSystemAccessRule(system,
                FileSystemRights.FullControl, AccessControlType.Allow));

            info.SetAccessControl(sec);
            return true;
        }
        catch (Exception ex)
        {
            // Log the failure at WARN level; re-throw if elevated (fundamental ACL failure).
            var msg = $"Failed to lock down ACLs on {path}: {ex.Message}";
            log?.Warn(msg);

            // If running elevated, this is a real problem; surface it for the UI to handle.
            if (OperatingSystem.IsWindows() && IsRunningElevated())
                throw;

            return false; // non-elevated: swallow and signal failure to caller
        }
#pragma warning restore CA1416
    }

    private static bool IsRunningElevated()
    {
        try
        {
            var identity = System.Security.Principal.WindowsIdentity.GetCurrent();
            var principal = new System.Security.Principal.WindowsPrincipal(identity);
            return principal.IsInRole(System.Security.Principal.WindowsBuiltInRole.Administrator);
        }
        catch { return false; }
    }
}
