using System;
using AIBox.FirstRun.Services;
using Xunit;

namespace AIBox.FirstRun.Tests;

/// <summary>
/// Known-answer tests (KATs) for <see cref="Ed25519Verifier"/>.
///
/// The test vectors below were generated by a reference Python implementation
/// of RFC 8032 Ed25519 (the same algorithm as Ed25519Verifier.cs) and verified
/// to be self-consistent.  Three vectors cover:
///   VECTOR_A — empty message, all-zero seed
///   VECTOR_B — single-byte message 0x72, seed starting with 0x01
///   VECTOR_C — two-byte message 0xAF82, seed starting with 0x02
///
/// The Python reference code used:
///   q = 2**255 - 19; L = 2**252 + 27742317777372353535851937790883648493
///   SHA-512 key expansion with standard Ed25519 scalar clamping
///   Extended twisted Edwards addition / scalar multiplication
///   Little-endian point compression (y | sign(x)<<255)
///   h = SHA-512(R || A || M) mod L
///   s = (r + h·a) mod L
///
/// The seeds (private keys) were:
///   VECTOR_A: 0x00 * 32
///   VECTOR_B: 0x01 followed by 0x00 * 31
///   VECTOR_C: 0x02 followed by 0x00 * 31
/// </summary>
public sealed class Ed25519VerifierTests
{
    // -------------------------------------------------------------------------
    // VECTOR A — empty message, all-zero seed
    // -------------------------------------------------------------------------

    private const string VecA_PubKey =
        "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29";
    private const string VecA_Sig =
        "8f895b3cafe2c9506039d0e2a66382568004674fe8d237785092e40d6aaf483e" +
        "4fc60168705f31f101596138ce21aa357c0d32a064f423dc3ee4aa3abf53f803";
    // Message: empty (zero bytes)

    [Fact]
    public void Verify_VectorA_EmptyMessage_ReturnsTrue()
    {
        var pubKey = FromHex(VecA_PubKey);
        var sig = FromHex(VecA_Sig);
        Assert.True(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig),
            "Vector A (empty message) verification must return true.");
    }

    // -------------------------------------------------------------------------
    // VECTOR B — single-byte message 0x72
    // -------------------------------------------------------------------------

    private const string VecB_PubKey =
        "cecc1507dc1ddd7295951c290888f095adb9044d1b73d696e6df065d683bd4fc";
    private const string VecB_Sig =
        "b730b151510c319d35a487a4f3d8ed8ebf2e32a67545d10b778ad0c0cb1eb539" +
        "62a29fcb8f74f88c710718976260e22ebe20de6e1ed9cdbc48e1918cde854e0c";
    private static readonly byte[] VecB_Message = new byte[] { 0x72 };

    [Fact]
    public void Verify_VectorB_SingleByteMessage_ReturnsTrue()
    {
        var pubKey = FromHex(VecB_PubKey);
        var sig = FromHex(VecB_Sig);
        Assert.True(Ed25519Verifier.Verify(pubKey, VecB_Message, sig),
            "Vector B (single byte 0x72) verification must return true.");
    }

    // -------------------------------------------------------------------------
    // VECTOR C — two-byte message 0xAF 0x82
    // -------------------------------------------------------------------------

    private const string VecC_PubKey =
        "6b79c57e6a095239282c04818e96112f3f03a4001ba97a564c23852a3f1ea5fc";
    private const string VecC_Sig =
        "e1d74ee9b89c19154f247c786bce0fd5ff414d4d8486b62b1c8d5564debd9b58" +
        "62ae6c889b24409680f6fee16195dedfa939df56ab6161e00d3e12e211a17e03";
    private static readonly byte[] VecC_Message = new byte[] { 0xaf, 0x82 };

    [Fact]
    public void Verify_VectorC_TwoByteMessage_ReturnsTrue()
    {
        var pubKey = FromHex(VecC_PubKey);
        var sig = FromHex(VecC_Sig);
        Assert.True(Ed25519Verifier.Verify(pubKey, VecC_Message, sig),
            "Vector C (two bytes 0xAF82) verification must return true.");
    }

    // -------------------------------------------------------------------------
    // Negative tests
    // -------------------------------------------------------------------------

    [Fact]
    public void Verify_FlippedSignatureBit_ReturnsFalse()
    {
        var pubKey = FromHex(VecA_PubKey);
        var sig = FromHex(VecA_Sig).ToArray();
        // Flip one bit in the R half of the signature.
        sig[16] ^= 0x01;
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig),
            "A signature with one flipped bit must be rejected.");
    }

    [Fact]
    public void Verify_FlippedSignatureBitInS_ReturnsFalse()
    {
        var pubKey = FromHex(VecA_PubKey);
        var sig = FromHex(VecA_Sig).ToArray();
        // Flip one bit in the S half (bytes 32–63).
        sig[48] ^= 0x04;
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig));
    }

    [Fact]
    public void Verify_TruncatedSignature_ReturnsFalse()
    {
        var pubKey = FromHex(VecA_PubKey);
        // Exactly 63 bytes — one short of the required 64.
        var sig = FromHex(VecA_Sig)[..63];
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig),
            "A truncated (63-byte) signature must be rejected.");
    }

    [Fact]
    public void Verify_ZeroLengthSignature_ReturnsFalse()
    {
        var pubKey = FromHex(VecA_PubKey);
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty));
    }

    [Fact]
    public void Verify_AllZerosPublicKey_ReturnsFalse()
    {
        // All-zeros public key does not correspond to any valid point in the group.
        var pubKey = new byte[32];
        var sig = FromHex(VecA_Sig);
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig));
    }

    [Fact]
    public void Verify_WrongPublicKey_ReturnsFalse()
    {
        // Use Vector B's public key against Vector A's signature — must fail.
        var pubKey = FromHex(VecB_PubKey);
        var sig = FromHex(VecA_Sig);
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig));
    }

    [Fact]
    public void Verify_ShortPublicKey_ReturnsFalse()
    {
        // 16 bytes instead of 32 bytes.
        var pubKey = FromHex(VecA_PubKey)[..16];
        var sig = FromHex(VecA_Sig);
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig));
    }

    [Fact]
    public void Verify_CorrectSigWrongMessage_ReturnsFalse()
    {
        var pubKey = FromHex(VecB_PubKey);
        var sig = FromHex(VecB_Sig);
        var wrongMsg = new byte[] { 0x73 }; // one byte off from 0x72
        Assert.False(Ed25519Verifier.Verify(pubKey, wrongMsg, sig));
    }

    [Fact]
    public void Verify_AllZerosSignature_ReturnsFalse()
    {
        var pubKey = FromHex(VecA_PubKey);
        var sig = new byte[64]; // all zeros
        Assert.False(Ed25519Verifier.Verify(pubKey, ReadOnlySpan<byte>.Empty, sig));
    }

    // -------------------------------------------------------------------------
    // RFC 8032 §7.1 Official Known-Answer Test Vectors
    // -------------------------------------------------------------------------
    // These are the canonical IETF test vectors from RFC 8032 §7.1.
    // Public keys and signatures are used directly as published; secret keys
    // are listed for reference only (not used at verification time).
    // -------------------------------------------------------------------------

    // RFC 8032 §7.1 TEST 1 — empty message
    // SECRET KEY: 9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60
    private const string Rfc8032_T1_PubKey =
        "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";
    private const string Rfc8032_T1_Sig =
        "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155" +
        "5fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b";
    // Message: empty

    [Fact]
    public void Rfc8032_Test1_EmptyMessage_ReturnsTrue()
    {
        var pk = FromHex(Rfc8032_T1_PubKey);
        var sig = FromHex(Rfc8032_T1_Sig);
        Assert.True(Ed25519Verifier.Verify(pk, ReadOnlySpan<byte>.Empty, sig),
            "RFC 8032 §7.1 Test 1 (empty message) must verify.");
    }

    [Fact]
    public void Rfc8032_Test1_FlippedSignatureByte_ReturnsFalse()
    {
        var pk = FromHex(Rfc8032_T1_PubKey);
        var sig = FromHex(Rfc8032_T1_Sig).ToArray();
        sig[16] ^= 0x01;
        Assert.False(Ed25519Verifier.Verify(pk, ReadOnlySpan<byte>.Empty, sig),
            "RFC 8032 §7.1 Test 1: flipped signature byte must be rejected.");
    }

    [Fact]
    public void Rfc8032_Test1_WrongMessage_ReturnsFalse()
    {
        var pk = FromHex(Rfc8032_T1_PubKey);
        var sig = FromHex(Rfc8032_T1_Sig);
        var wrongMsg = new byte[] { 0x00 };
        Assert.False(Ed25519Verifier.Verify(pk, wrongMsg, sig),
            "RFC 8032 §7.1 Test 1: non-empty message against empty-message sig must be rejected.");
    }

    // RFC 8032 §7.1 TEST 2 — 1-byte message 0x72
    // SECRET KEY: 4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb
    private const string Rfc8032_T2_PubKey =
        "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c";
    private const string Rfc8032_T2_Sig =
        "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da" +
        "085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00";
    private static readonly byte[] Rfc8032_T2_Message = new byte[] { 0x72 };

    [Fact]
    public void Rfc8032_Test2_OneByte_ReturnsTrue()
    {
        var pk = FromHex(Rfc8032_T2_PubKey);
        var sig = FromHex(Rfc8032_T2_Sig);
        Assert.True(Ed25519Verifier.Verify(pk, Rfc8032_T2_Message, sig),
            "RFC 8032 §7.1 Test 2 (message=0x72) must verify.");
    }

    [Fact]
    public void Rfc8032_Test2_FlippedSignatureByte_ReturnsFalse()
    {
        var pk = FromHex(Rfc8032_T2_PubKey);
        var sig = FromHex(Rfc8032_T2_Sig).ToArray();
        sig[48] ^= 0x04;
        Assert.False(Ed25519Verifier.Verify(pk, Rfc8032_T2_Message, sig),
            "RFC 8032 §7.1 Test 2: flipped signature byte must be rejected.");
    }

    [Fact]
    public void Rfc8032_Test2_WrongMessage_ReturnsFalse()
    {
        var pk = FromHex(Rfc8032_T2_PubKey);
        var sig = FromHex(Rfc8032_T2_Sig);
        var wrongMsg = new byte[] { 0x73 }; // one off from 0x72
        Assert.False(Ed25519Verifier.Verify(pk, wrongMsg, sig),
            "RFC 8032 §7.1 Test 2: wrong message byte must be rejected.");
    }

    // RFC 8032 §7.1 TEST 3 — 2-byte message 0xAF 0x82
    // SECRET KEY: c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7
    private const string Rfc8032_T3_PubKey =
        "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025";
    private const string Rfc8032_T3_Sig =
        "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac" +
        "18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a";
    private static readonly byte[] Rfc8032_T3_Message = new byte[] { 0xaf, 0x82 };

    [Fact]
    public void Rfc8032_Test3_TwoBytes_ReturnsTrue()
    {
        var pk = FromHex(Rfc8032_T3_PubKey);
        var sig = FromHex(Rfc8032_T3_Sig);
        Assert.True(Ed25519Verifier.Verify(pk, Rfc8032_T3_Message, sig),
            "RFC 8032 §7.1 Test 3 (message=0xAF82) must verify.");
    }

    [Fact]
    public void Rfc8032_Test3_FlippedSignatureByte_ReturnsFalse()
    {
        var pk = FromHex(Rfc8032_T3_PubKey);
        var sig = FromHex(Rfc8032_T3_Sig).ToArray();
        sig[0] ^= 0x80;
        Assert.False(Ed25519Verifier.Verify(pk, Rfc8032_T3_Message, sig),
            "RFC 8032 §7.1 Test 3: flipped signature byte must be rejected.");
    }

    [Fact]
    public void Rfc8032_Test3_WrongMessage_ReturnsFalse()
    {
        var pk = FromHex(Rfc8032_T3_PubKey);
        var sig = FromHex(Rfc8032_T3_Sig);
        var wrongMsg = new byte[] { 0xaf }; // truncated to one byte
        Assert.False(Ed25519Verifier.Verify(pk, wrongMsg, sig),
            "RFC 8032 §7.1 Test 3: truncated message must be rejected.");
    }

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------

    private static ReadOnlySpan<byte> FromHex(string hex) =>
        Convert.FromHexString(hex);
}
