; AIBox-Setup.iss — Inno Setup script for Phase A.
;
; Builds the AIBox-Setup-<version>.exe that lays down the install tree,
; runs the bundled Docker Desktop MSI, registers the uninstall entry,
; and writes %ProgramData%\AIBox\install-state.json with phase_a_complete=true.
;
; What this script DOES NOT do:
;   - generate the .env (waits for the admin password in Phase C)
;   - docker compose pull (daemon may not be running yet)
;   - download content (~100 GB is the First Run app's job)
;   - register the autostart task (Phase C does this after smoke test)
;
; Build with: iscc.exe /Dversion=1.0.0 AIBox.iss
;             (or via .github/workflows/release.yml)

#ifndef version
  #define version "0.0.1"
#endif

#define MyAppName      "AIBox"
#define MyAppPublisher "Project Puente AI"
#define MyAppURL       "https://github.com/ProjectPuente/aibox"
#define MyAppVersion   version

[Setup]
AppId={{8C2D7C09-2C13-4F0B-9F88-9D2E3E7D9F12}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}/releases
DefaultDirName=C:\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableWelcomePage=no
DisableProgramGroupPage=yes
ArchitecturesInstallIn64BitMode=x64
ArchitecturesAllowed=x64
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=
OutputBaseFilename=AIBox-Setup-{#MyAppVersion}
OutputDir=..\dist
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
WizardImageFile=branding\banner.bmp
WizardSmallImageFile=branding\banner-small.bmp
SetupIconFile=branding\app.ico
UninstallDisplayIcon={app}\app.ico
LicenseFile=branding\LICENSE.rtf
InfoBeforeFile=branding\PREINSTALL.rtf
CloseApplications=yes
RestartApplications=no
MinVersion=10.0.19041

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full"; Description: "Full install (recommended)"

[Components]
Name: "code";       Description: "AIBox application files"; Types: full; Flags: fixed
Name: "firstrun";   Description: "AIBox First Run app";    Types: full; Flags: fixed
Name: "docker";     Description: "Docker Desktop (bundled MSI)"; Types: full

[Files]
; The AIBox source tree (aibox/) — excludes runtime data dirs which are
; populated by the First Run app at download time. ../../../ resolves to
; the repo root from this script's directory.
Source: "..\..\..\aibox\stack\*";   DestDir: "{app}\aibox\stack";        Flags: ignoreversion recursesubdirs createallsubdirs; Components: code
Source: "..\..\..\aibox\tools\*";   DestDir: "{app}\aibox\tools";        Flags: ignoreversion recursesubdirs createallsubdirs; Components: code
Source: "..\..\..\aibox\scripts\*"; DestDir: "{app}\aibox\scripts";      Flags: ignoreversion recursesubdirs createallsubdirs; Components: code; Excludes: "*.pyc,__pycache__\*"
Source: "..\..\..\aibox\docs\*";    DestDir: "{app}\aibox\docs";         Flags: ignoreversion recursesubdirs createallsubdirs; Components: code
Source: "..\..\..\aibox\README.md"; DestDir: "{app}\aibox";              Flags: ignoreversion; Components: code
Source: "..\..\..\aibox\requirements.txt"; DestDir: "{app}\aibox";       Flags: ignoreversion; Components: code

; Bundled signed manifest. The First Run app prefers this over the URL fetch
; (offline-first). CI builds re-sign + re-stage these against the same paths.
Source: "..\dist\manifest-{#version}.json";     DestDir: "{app}\manifest"; Flags: ignoreversion; Components: code
Source: "..\dist\manifest-{#version}.json.sig"; DestDir: "{app}\manifest"; Flags: ignoreversion; Components: code

; Release commit pin — generated by CI before iscc runs.
#ifexist "..\dist\stage\RELEASE_COMMIT.txt"
Source: "..\dist\stage\RELEASE_COMMIT.txt"; DestDir: "{app}\aibox"; Flags: ignoreversion; Components: code
#else
#pragma message "WARN: dist\stage\RELEASE_COMMIT.txt not staged — local build will be incomplete"
#endif

; First Run app (compiled WPF binaries).
; #ifexist checks a specific file inside the directory because Inno's
; preprocessor #ifexist only matches files, not directory paths.
#ifexist "..\dist\stage\first-run\AIBox First Run.exe"
Source: "..\dist\stage\first-run\*"; DestDir: "{app}\AIBoxFirstRun"; \
  Flags: ignoreversion recursesubdirs createallsubdirs; Components: firstrun
#else
#pragma message "WARN: dist\stage\first-run\AIBox First Run.exe not staged — local build will be incomplete"
#endif

; Bundled Docker Desktop installer (downloaded fresh by CI, hash-verified)
#ifexist "..\dist\stage\DockerDesktopInstaller.exe"
Source: "..\dist\stage\DockerDesktopInstaller.exe"; DestDir: "{tmp}"; \
  Flags: deleteafterinstall; Components: docker
#else
#pragma message "WARN: dist\stage\DockerDesktopInstaller.exe not staged — local build will be incomplete"
#endif

; NVIDIA preflight shim
#ifexist "..\dist\stage\nvidia-probe.exe"
Source: "..\dist\stage\nvidia-probe.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
#else
#pragma message "WARN: dist\stage\nvidia-probe.exe not staged — local build will be incomplete"
#endif

; Branding
Source: "branding\app.ico"; DestDir: "{app}"; Flags: ignoreversion

[Dirs]
; Phase A data root + log dir. Phase B/C will populate further.
; Directories inherit parent ACLs from %ProgramData%. Explicit Permissions
; are unnecessary and may cause issues with non-standard Inno syntax.
Name: "{commonappdata}\AIBox"
Name: "{commonappdata}\AIBox\logs"
Name: "{commonappdata}\AIBox\tmp"

[Icons]
Name: "{commondesktop}\AIBox First Run"; Filename: "{app}\AIBoxFirstRun\AIBox First Run.exe"; \
  IconFilename: "{app}\app.ico"; Comment: "Download AIBox content and finish setup."
Name: "{group}\AIBox First Run"; Filename: "{app}\AIBoxFirstRun\AIBox First Run.exe"; \
  IconFilename: "{app}\app.ico"
Name: "{group}\AIBox Documentation"; Filename: "{app}\aibox\docs"

[Run]
; Docker Desktop silent install.
; We invoke via cmd.exe so we can capture the exit code in a sentinel file.
; Exit code 3010 = success + reboot required (Windows Installer convention).
; Exit code 0    = success, no reboot required.
; Any other code = failure (surfaced by First Run smoke test, not blocked here).
; HandleDockerInstallResult() reads the sentinel and sets NeedReboot accordingly.
Filename: "{cmd}"; \
  Parameters: "/C ""{tmp}\DockerDesktopInstaller.exe"" install --quiet --accept-license & echo %ERRORLEVEL% > ""{tmp}\docker_install_result.txt"""; \
  StatusMsg: "Installing Docker Desktop (this can take several minutes)..."; \
  Flags: waituntilterminated; Components: docker; Check: NeedsDockerInstall; \
  AfterInstall: HandleDockerInstallResult()

[UninstallRun]
; The full data-side cleanup (downloaded content, .env secrets, hosts entry,
; mobile-hotspot config, scheduled task) is handled by a separate
; AIBoxUninstaller.exe so the user can opt in to each piece. Inno's
; built-in uninstaller only removes the install tree.
Filename: "{app}\AIBoxFirstRun\AIBoxUninstaller.exe"; \
  Parameters: "--from-inno"; \
  Flags: runhidden; \
  RunOnceId: "AIBoxDataCleanup"

[Code]
const
  REGKEY_RUNONCE = 'Software\Microsoft\Windows\CurrentVersion\RunOnce';
  STATE_FILE_REL = 'AIBox\install-state.json';

var
  PreflightPage: TWizardPage;
  PassedPreflight: Boolean;
  NeedReboot: Boolean;

function CheckNvidiaGpu(): Boolean;
var
  ResultCode: Integer;
  Output: AnsiString;
  TmpFile: String;
begin
  Result := False;
  TmpFile := ExpandConstant('{tmp}\nvidia-check.txt');
  // Use the bundled probe — it's a tiny binary that wraps DXGI / nvidia-smi
  // detection. Returns 0 on NVIDIA GPU found, nonzero otherwise.
  if Exec(ExpandConstant('{tmp}\nvidia-probe.exe'), '', '', SW_HIDE,
          ewWaitUntilTerminated, ResultCode) then
    Result := (ResultCode = 0)
  else
    Result := False;
end;

function CheckRamGB(MinGB: Integer): Boolean;
var
  ResultCode: Integer;
  TmpFile: String;
  RamBytesAnsi: AnsiString;
  RamBytes: String;
  RamGB: Int64;
begin
  { Attempt WMI query via PowerShell to get total physical RAM.
    This is more reliable than direct API calls in Inno Pascal.
    If the query fails or returns 0, we pass the check and let Docker
    Desktop's own checks catch missing RAM at runtime. }
  Result := False;
  TmpFile := ExpandConstant('{tmp}\ram_check.txt');

  { Quote TmpFile with embedded single quotes so PowerShell tolerates a
    username with spaces (e.g. C:\Users\First Last\AppData\...). The outer
    PowerShell argument is wrapped in double quotes, so single quotes are
    the only safe nesting choice. }
  if Exec(ExpandConstant('{cmd}'), '/C powershell -NoProfile -Command ' +
          '"(Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory | Out-File -Encoding ASCII ''' +
          TmpFile + '''" 2>NUL', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    if ResultCode = 0 then
    begin
      try
        if LoadStringFromFile(TmpFile, RamBytesAnsi) then
        begin
          RamBytes := Trim(String(RamBytesAnsi));
          if RamBytes <> '' then
          begin
            RamGB := StrToInt64(RamBytes) div (1024 * 1024 * 1024);
            Result := (RamGB >= MinGB);
          end
          else
            { WMI succeeded but returned nothing — suspicious. Refuse the
              check rather than silently passing a 4 GB box. }
            Result := False;
        end
        else
          { File read failed (antivirus, ACLs, etc.). Infrastructure failure,
            not a RAM problem — stay permissive. }
          Result := True;
      except
        Result := True;  { Parse error; let Docker's own check catch RAM. }
      end;
    end
    else
      Result := True;  { PowerShell exit nonzero — infrastructure issue, permissive. }
  end
  else
    Result := True;  { Exec failed entirely — infrastructure issue, permissive. }
end;

function CheckFreeDiskGB(Drive: String; MinGB: Integer): Boolean;
var
  Free64, Total64: Int64;
begin
  Result := False;
  { GetSpaceOnDisk64(Path, var FreeBytes, var TotalBytes): Boolean }
  if GetSpaceOnDisk64(Drive, Free64, Total64) then
    Result := (Free64 >= (Int64(MinGB) * 1024 * 1024 * 1024));
end;

function CheckVirtualization(): Boolean;
begin
  // Inno doesn't expose CPU feature bits directly; we rely on the fact that
  // Docker Desktop's MSI itself will refuse to install without VT-x/SVM, so
  // we surface a more helpful preflight message instead of bailing later.
  // For the first cut we always pass this check and let Docker's own
  // diagnostics catch a misconfigured BIOS. A future improvement is to
  // shell out to "systeminfo /fo csv" and parse the Hyper-V Requirements row.
  Result := True;
end;

function NeedsDockerInstall(): Boolean;
var
  ResultCode: Integer;
begin
  // If `docker --version` exits 0, assume Docker is installed and skip.
  Result := True;
  if Exec(ExpandConstant('{cmd}'), '/C docker --version >NUL 2>&1', '',
          SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    if ResultCode = 0 then Result := False;
end;

procedure InitializeWizard();
var
  Label1: TLabel;
  HasNvidia, HasRam, HasDisk, HasVirt: Boolean;
  AllPassed: Boolean;
  CheckLine: String;
  PreflightText: TMemo;
begin
  PreflightPage := CreateCustomPage(wpWelcome, 'System check',
    'AIBox needs an NVIDIA GPU, ample RAM, and free disk space.');

  Label1 := TLabel.Create(PreflightPage);
  Label1.Parent := PreflightPage.Surface;
  Label1.Left := 0;
  Label1.Top := 0;
  Label1.Width := PreflightPage.SurfaceWidth;
  Label1.Caption :=
    'Each item below is required. NVIDIA GPU is a hard requirement — '
    + 'AIBox uses CUDA-accelerated llama.cpp and bge-m3 embeddings, and '
    + 'will not function on CPU-only or non-NVIDIA hardware.';
  Label1.WordWrap := True;
  Label1.AutoSize := False;
  Label1.Height := 48;

  PreflightText := TMemo.Create(PreflightPage);
  PreflightText.Parent := PreflightPage.Surface;
  PreflightText.Left := 0;
  PreflightText.Top := 60;
  PreflightText.Width := PreflightPage.SurfaceWidth;
  PreflightText.Height := PreflightPage.SurfaceHeight - 100;
  PreflightText.ReadOnly := True;
  PreflightText.ScrollBars := ssVertical;

  // Run all checks now so the user sees results immediately.
  HasNvidia := CheckNvidiaGpu();
  HasRam    := CheckRamGB(16);
  HasDisk   := CheckFreeDiskGB('C:', 150);
  HasVirt   := CheckVirtualization();
  AllPassed := HasNvidia and HasRam and HasDisk and HasVirt;
  PassedPreflight := AllPassed;

  if HasNvidia then CheckLine := '[OK]    ' else CheckLine := '[FAIL]  ';
  PreflightText.Lines.Add(CheckLine + 'NVIDIA GPU (CUDA-capable)');
  if not HasNvidia then
    PreflightText.Lines.Add('         No CUDA-capable NVIDIA GPU detected. AIBox cannot run on this machine.');

  if HasRam then CheckLine := '[OK]    ' else CheckLine := '[FAIL]  ';
  PreflightText.Lines.Add(CheckLine + '16 GB or more RAM');
  if not HasRam then
    PreflightText.Lines.Add('         Less than 16 GB RAM detected. The LLM will not load reliably.');

  if HasDisk then CheckLine := '[OK]    ' else CheckLine := '[FAIL]  ';
  PreflightText.Lines.Add(CheckLine + '150 GB or more free on C:');
  if not HasDisk then
    PreflightText.Lines.Add('         AIBox needs ~100 GB for content and ~50 GB headroom. Free up space and re-run.');

  if HasVirt then CheckLine := '[OK]    ' else CheckLine := '[FAIL]  ';
  PreflightText.Lines.Add(CheckLine + 'Virtualization (VT-x / SVM) for Docker Desktop');
  if not HasVirt then
    PreflightText.Lines.Add('         Enable VT-x or AMD-V in your BIOS/UEFI before installing.');

  PreflightText.Lines.Add('');
  if AllPassed then
    PreflightText.Lines.Add('All checks passed. Click Next to continue.')
  else
    PreflightText.Lines.Add('One or more checks failed. Resolve them before continuing.');
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (PreflightPage <> nil) and (CurPageID = PreflightPage.ID) then
  begin
    if not PassedPreflight then
    begin
      MsgBox(
        'AIBox cannot install on this machine until the failed preflight '
        + 'items are resolved. NVIDIA GPU is a hard requirement.',
        mbCriticalError, MB_OK);
      Result := False;
    end;
  end;
end;

procedure WriteInstallState();
var
  StateDir, StatePath, Json: String;
  InstallRootEsc, DataRootEsc: String;
begin
  StateDir := ExpandConstant('{commonappdata}\AIBox');
  StatePath := StateDir + '\install-state.json';
  ForceDirectories(StateDir);

  { StringChangeEx mutates its first arg (var) and returns the replacement
    count, so it must operate on locals — not on inline expressions. }
  InstallRootEsc := ExpandConstant('{app}');
  StringChangeEx(InstallRootEsc, '\', '\\', True);
  DataRootEsc := StateDir;
  StringChangeEx(DataRootEsc, '\', '\\', True);

  Json :=
    '{' + #13#10 +
    '  "schema_version": 1,' + #13#10 +
    '  "version": "' + ExpandConstant('{#MyAppVersion}') + '",' + #13#10 +
    '  "install_root": "' + InstallRootEsc + '",' + #13#10 +
    '  "data_root": "' + DataRootEsc + '",' + #13#10 +
    '  "phase_a_complete": true,' + #13#10 +
    '  "phase_b_complete": false,' + #13#10 +
    '  "phase_c_complete": false,' + #13#10 +
    '  "phase_c_step": "",' + #13#10 +
    '  "items": {},' + #13#10 +
    '  "last_saved_at_utc": ""' + #13#10 +
    '}' + #13#10;

  SaveStringToFile(StatePath, Json, False);
end;

procedure RegisterRebootResume();
var
  ExePath: String;
begin
  // If Docker Desktop requested a reboot, leave a RunOnce that relaunches
  // the wizard post-reboot so the user can pick up where they left off.
  ExePath := ExpandConstant('{srcexe}');
  RegWriteStringValue(HKEY_LOCAL_MACHINE, REGKEY_RUNONCE, 'AIBoxResumeInstall',
    '"' + ExePath + '" /SILENT /SUPPRESSMSGBOXES');
end;

procedure HandleDockerInstallResult();
var
  SentinelPath: String;
  ExitCodeAnsi: AnsiString;
  ExitCodeStr: String;
  ExitCode: Integer;
begin
  { Read the sentinel file written by the cmd.exe wrapper in [Run].
    The file contains the %ERRORLEVEL% of DockerDesktopInstaller.exe.
    Docker Desktop exit codes:
      0    = success, no reboot required
      3010 = success, reboot required (standard Windows Installer convention)
      other = installation failed (let First Run smoke test surface the error)
    If the sentinel is missing or unparseable we assume reboot is needed
    (conservative fallback — better to reboot unnecessarily than to skip it). }
  SentinelPath := ExpandConstant('{tmp}\docker_install_result.txt');

  NeedReboot := True;  { default: assume reboot needed }

  if FileExists(SentinelPath) and LoadStringFromFile(SentinelPath, ExitCodeAnsi) then
  begin
    ExitCodeStr := Trim(String(ExitCodeAnsi));
    if ExitCodeStr <> '' then
    begin
      try
        ExitCode := StrToInt(ExitCodeStr);
        if ExitCode = 0 then
          NeedReboot := False      { clean success, no reboot }
        else if ExitCode = 3010 then
          NeedReboot := True       { success + reboot required }
        else
          NeedReboot := True;      { non-zero = error or unknown; keep reboot as safe default }
      except
        NeedReboot := True;        { parse error; fall back to reboot }
      end;
    end;
    // Sentinel read; leave the file for diagnostic purposes — it lives in
    // the temp directory which is cleaned up by Inno after the wizard exits.
  end;
  // else: sentinel missing means cmd.exe wrapper itself failed to run;
  // fall back to NeedReboot := True set above.

  if NeedReboot then
    RegisterRebootResume();
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    WriteInstallState();
    { Reboot decision was made by HandleDockerInstallResult() in the [Run]
      phase (AfterInstall:). Inno calls NeedRestart() below to decide whether
      to prompt for restart. }
  end;
end;

function NeedRestart(): Boolean;
begin
  { Inno invokes this callback at the end of the install flow. We return
    the value that HandleDockerInstallResult() computed earlier in [Run]. }
  Result := NeedReboot;
end;
